# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://isorsa.com
title: Isorsa
email: kim@isorsa.com
author: Isorsa
description: 'Software consulting'
copyright: 'Copyright &copy; 2016 Isorsa. All Rights Reserved.'
credits: 'Credits: <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/
  - title: github
    url: https://github.com/isorsa
  - title: linkedin
    url: https://www.linkedin.com/in/sergey-kim-2195183
